- src/components/BusinessBrandBUSIDetail/index.js
> Update: businessBrandBusinessDetail

- src/components/Settings/index.js
Story: https://app.asana.com/0/1200268243113852/1201127719163701
> Feat: hide distanceUnitKM

- src/components/AdvancedReports/index.js
Story: https://app.asana.com/0/1200268243113852/1201318769610743
> Update: reports date time

- src/components/AnalyticsBusinessFilter/index.js
> Update: businessFilter

- src/components/DashboardOrdersList/index.js
- src/components/OrdersFilter/index.js
- src/components/SettingsList/index.js
Story: https://app.asana.com/0/1200268243113852/1201355607976149
> [Update]: Orders section

- src/components/BusinessCategoryEdit/index.js
Story: https://app.asana.com/0/0/1201366418487247/f
> [Improve] create subcategory

- src/components/BusinessMenuOptions/index.js
STORY: https://app.asana.com/0/1198717964402573/1201389323993579
> [Fix] bugs

- src/components/ReportsDriverFilter/index.js
Story: https://app.asana.com/0/1200268243113852/1201367565790393
> Update: reportsDriverfilter

- src/components/EnterprisePromontionList/index.js
- src/components/EnterprisePromotionDetails/index.js
STORY: https://app.asana.com/0/1198717964402573/1201481104556375
> [Fix] bugs for advanced offers

- src/components/BusinessMenuOptions/index.js
STORY: https://app.asana.com/0/1198717964402573/1201526549520043
> [Fix] feedback

- src/components/InvoiceDriverManager/index.js
STORY: https://app.asana.com/0/1198717964402573/1201509014922780
> [Fix] feedback for drivers invoice

- src/components/BusinessProductsCategoyDetails/index.js
- src/components/ProductDetatils/index.js
Story: https://app.asana.com/0/0/1200735055331834/f
> [Improvement] Seo Options

- src/components/BusinessProductsListing/index.js
- src/components/EnterprisePromotionDetails/index.js
ASANA TASK: https://app.asana.com/0/0/1201728766513282/f
Video: https://d.pr/v/7tzwRa
> Change product-promotion structure and update slug to show products

- src/components/SingleBusinessProduct/index.js
STORY: https://app.asana.com/0/1198717964402573/1201894042190284
> [Update] Allow drag and drop to the end of bottom

- src/components/BusinessDetails/index.js
STORY: https://app.asana.com/0/1198717964402573/1201928750178114
> [Fix] crash error

- src/components/ReportsBrandFilter/index.js
STORY: https://app.asana.com/0/1198717964402573/1201931136690862
> [Update] Brand filter for business owner

- src/components/DashboardBusinessList/index.js
STORY: https://app.asana.com/0/1198717964402573/1201957658179748
> [Fix] feedback for businesses

- src/components/ProductExtraOptions/index.js
STORY: https://app.asana.com/0/1198717964402573/1201990987736148
> [Update] add option

- src/components/EnterprisePromotionDetails/index.js
Story: https://app.asana.com/0/1201115702325003/1202013353877498
Video: https://d.pr/v/fPKUUp
> [FIX] promotions states when new promotions

- src/components/BusinessProductsCategoyDetails/index.js
Story: https://app.asana.com/0/1200268243113852/1202050716758512
> Update: category description

- src/components/OrdersManage/index.js
- src/contexts/UtilsContext/index.js
STORY: https://app.asana.com/0/1198717964402573/1202064982696973
> [Add] new order statues

- src/components/BusinessDeliveryDetails/index.js
STORY: https://app.asana.com/0/1198717964402573/1202087724375464
> [Add] delivery zone enable/disable functionality

- src/components/EnterprisePromotionList/index.js
STORY: https://app.asana.com/0/1198717964402573/1202013201160304
> [Add] attribute for include_options condition

- src/components/ProductExtraOptionDetails/index.js
Story: https://app.asana.com/0/1198717964402573/1201957658179743
> [Update] product extra option details

- src/components/SingleRecoveryNotification/index.js
Story: https://app.asana.com/0/1200268243113852/1201588481171762
> Update: SingleRecoveryNotification

- src/components/EnterprisePromotionList/index.js
STORY: https://app.asana.com/0/1198717964402573/1202118918185899
> [Fix] page size

- src/components/BusinessProductsListing/index.js
STORY: https://app.asana.com/0/1198717964402573/1201936820213213
> [Add] initiate state for none slug

- src/components/ProductExtraOptions/index.js
STORY: https://app.asana.com/0/1198717964402573/1201990987736152
> [Update] option update

- src/components/ProductExtraOptions/index.js
STORY: https://app.asana.com/0/1198717964402573/1201990987736152
> [Fix] validation error

- src/components/SingleBusinessCategory/index.js
STORY: https://app.asana.com/0/1198717964402573/1202141091343500
> [Update] category reset

- src/components/OrdersManage/index.js
STORY: https://app.asana.com/0/1198717964402573/1202143272105040
> [Update] feedback for driver manager

- src/components/BusinessPaymethods/index.js
STORY: https://app.asana.com/0/1198717964402573/1202169048295961
> [Fix] Stripe save

- src/components/CampaignDetail/index.js
Story: https://app.asana.com/0/1200268243113852/1202163855981193
> Update: sales and marketing

- src/components/BusinessZoneGoogleMaps/index.js
STORY: https://app.asana.com/0/inbox/1198717964396322/1202120875514745/1202117293896062
> [Add] draw delivery zones for adding mode

- src/components/PointsWalletBusinessDetail/index.js
Story: https://app.asana.com/0/1200268243113852/1202149609255181
> Update: Loyalty

- src/components/EnterprisePromotionDetails/index.js
https://app.asana.com/0/1191220738645130/1202190614377517
> [FIX] autoclose and autosave offers without businesses

- src/components/CampaignDetail/index.js
Story: https://app.asana.com/0/1200268243113852/1202183333069167
> Campaign feedback

- src/components/BusinessProductsListing/index.js
STORY: https://app.asana.com/0/1198717964402573/1202100889553743
> [Fix] business products  for lazy load recommended

- src/components/OrderDetails/index.js
STORY: https://app.asana.com/0/1198717964402573/1202183674834024
> [Add] Order refund

- src/components/ProductExtraOptionDetails/index.js
- src/components/ProductExtraOptions/index.js
- src/components/ProductGallery/index.js
Story: https://app.asana.com/0/1200268243113852/1202237164968349
> Update: image crop

- src/components/LoginForm/index.js
STORY: https://app.asana.com/0/1198717964402573/1202230723660639
> [Fix] Recaptcha login

- src/components/OrderDetails/index.js
STORY: https://app.asana.com/0/1198717964402573/1202255156437435
> [Update] endpoint

- src/components/ProductDetailsAdvanced/index.js
Story: https://app.asana.com/0/home/1200550251832815/1202267634527175
Demo: https://d.pr/v/RLUYn0
> bug on update

- src/components/BusinessWalletsList/index.js
STORY: https://app.asana.com/0/1198717964402573/1202271877726667
> [Add] validate loyalty plan

- src/components/ProductExtras/index.js
STORY: https://app.asana.com/0/1198717964402573/1202275055102788
> [Add] allow product extra rank to drag and drop

- src/components/BusinessProductsCategoyDetails/index.js
Story: https://app.asana.com/0/1200268243113852/1202314921773483
> Update: businessProduct category

- src/components/EnterprisePromotionDetails/index.js
https://app.asana.com/0/1191220738645130/1202313937381827
> [FIX] create double promotions

- src/components/BusinessFormDetails/index.js
Story: https://app.asana.com/0/1200268243113852/1202342617303811
> Update: ribbon update

- src/components/ProductExtraOptionDetails/index.js
STORY: https://app.asana.com/0/1198717964402573/1202352983490902
> Export function

- src/components/ForgotPasswordForm/index.js
Story: https://app.asana.com/0/1200268243113852/1202295471114432
> [Update]: forgot password

- src/components/SettingsList/index.js
STORY: https://app.asana.com/0/1198717964402573/1202275034639048
> [Update] settings list

- src/components/ImporterForm/index.js
STORY: https://app.asana.com/0/1198717964402573/1202285052030909
> [update] importer form

- src/components/BusinessDeliveryZone/index.js
- src/components/BusinessZoneGoogleMaps/index.js
STORY: https://app.asana.com/0/inbox/1198717964396322/1202190954767788/1202462498782765
> [Add] KML file upload

- src/components/ImporterForm/index.js
STORY: https://app.asana.com/0/1198717964402573/1202285052024804
> [Update] importer for product options

- src/components/OrdersManage/index.js
Story: https://app.asana.com/0/home/1200550251832815/1202467383905259
> improvement ordermanage

- src/components/BusinessFormDetails/index.js
Story: https://app.asana.com/0/1200268243113852/1202482897647126
> Update: toast on business information

- src/components/SettingsList/index.js
Story: https://app.asana.com/0/home/1200550251832815/1202254753959593
Demo: https://d.pr/v/Fv3dsT
> feedback update invalid input

- src/components/LoyaltyLevelDetail/index.js
- src/components/PointsWalletLevels/index.js
- src/index.js
Story: https://app.asana.com/0/1200268243113852/1202548756349295
> Update: loyalty level

- src/components/ImporterForm/index.js
STORY: https://app.asana.com/0/1198717964402573/1202560902296997
> [Update] csv name

- src/components/CampaignDetail/index.js
Story: https://app.asana.com/0/1200268243113852/1202473893483668
> Update: marketing

- src/components/OrdersManage/index.js
Story: https://app.asana.com/0/home/1200550251832815/1202467383905259
> update socket handler

- src/components/DashboardOrdersList/index.js
- src/components/OrdersManage/index.js
Main Story: https://app.asana.com/0/home/1200550251832815/1202467383905259
Story: https://app.asana.com/0/home/1200550251832815/1202637702344593
Demo: https://d.pr/v/H7i9tY
> remove sub filter count

- src/components/UserDetails/index.js
Story: https://app.asana.com/0/1200550251832819/1202465862178685
> add driver schedules

- src/components/DriversList/index.js
STORY: https://app.asana.com/0/1198717964402573/1202714030865815
> [Add] drivers for order

- src/components/DashboardOrdersList/index.js
Story: https://app.asana.com/0/1200550251832819/1202764619973948
Demo:  https://d.pr/v/fyKRSO
> bug dashboard order filter

- src/components/DashboardOrdersList/index.js
> revert 302 PR

- src/components/Settings/index.js
Story: https://app.asana.com/0/1200268243113852/1202791288034103
> Update: hide advanced search

- src/components/OrdersManage/index.js
STORY: https://app.asana.com/0/1198717964402573/1202808937620949
> [Add] additional filter

- src/components/BusinessMenu/index.js
Story: https://app.asana.com/0/1200268243113852/1202800998453630
> Shared menu

- src/components/DriversList/index.js
STORY: https://app.asana.com/0/1198717964402573/1202863452017430
> [Fix] driver update

- src/components/SiteTheme/index.js
- src/index.js
STORY: https://app.asana.com/0/1198717964402573/1202544151068009
> [Feat] site theme

- src/components/EnterprisePromotionList/index.js
Story: https://app.asana.com/0/home/1200550251832815/1202871188266861
> update promotion rank

- src/components/BusinessZoneGoogleMaps/index.js
STORY: https://app.asana.com/0/1198717964402573/1202892928244711
> [Fix] crash

- src/components/EnterprisePromotionList/index.js
Story: https://app.asana.com/0/home/1200550251832815/1202871188266861
Demo: https://d.pr/v/fmEwSS
> improve promotion rank

- src/components/GiftCardsList/index.js
- src/components/UserWallet/index.js
- src/index.js
STORY: https://app.asana.com/0/1198717964402573/1201128260279148
> [Add] Gift cards

- src/components/DashboardOrdersList/index.js
- src/components/OrdersFilter/index.js
- src/components/OrdersManage/index.js
Story: https://app.asana.com/0/1200268243113852/1202955301108466
> Update: multi currency

- src/components/CampaignDetail/index.js
- src/components/CampaignDetailContent/index.js
- src/components/CampaignEmail/index.js
- src/index.js
Story: https://app.asana.com/0/1200268243113852/1202792087656221
> [Update]: marketing

- package.json
- src/components/LoginForm/index.js
- src/components/ReCaptcha/index.js
Story: https://app.asana.com/0/home/1200550251832815/1202895355715695
> Add recaptchav3

- src/components/DashboardOrdersList/index.js
Story: https://app.asana.com/0/home/1200550251832815/1202822050247341
> improve order manager

- src/components/DashboardBusinessList/index.js
Story: https://app.asana.com/0/home/1200550251832815/1202938731260382
> add refresh functionality in business

- src/components/BusinessProductsListing/index.js
Story: https://app.asana.com/0/home/1200550251832815/1202938731260386
> add refresh functionality in categories

- src/components/GiftCardsList/index.js
STORY: https://app.asana.com/0/1198717964402573/1202976229479472
> Feedback Gift cards

- src/components/EnterprisePromotionDetails/index.js
- src/components/EnterprisePromotionList/index.js
STORY: https://app.asana.com/0/1198717964402573/1202833227391904
> Improvement Advanced offers

- src/components/Settings/index.js
STORY: https://app.asana.com/0/1198717964402573/1202981354221777
> show the location setting

- src/components/BusinessProductCreator/index.js
- src/components/BusinessProductsCategoyDetails/index.js
- src/utils/index.js
STORY: https://app.asana.com/0/1198717964402573/1203142938023517
> [Add] Auto generated slug when adding new product or category

- src/components/OrderDetails/index.js
STORY: https://app.asana.com/0/1198717964402573/1203102112447535
> [Add] load message condition

- src/components/ResetPassword/index.js
Story: https://app.asana.com/0/1199511033583011/1203237884370429/f
Video: https://d.pr/v/QhQzkB
> [FEAT] Improvement password reset

- src/components/GoogleAutocompleteInput/index.js
STORY: https://app.asana.com/0/1198717964402573/1203137845562288
> [Fix] auto fill disable by 1Password extension

- src/components/AdBannersList/index.js
- src/components/BannerDetails/index.js
- src/index.js
STORY: https://app.asana.com/0/1198717964402573/1201184519566876
> [Feat] Ad banners

- src/components/LoginForm/index.js
STORY: https://app.asana.com/0/1198717964402573/1203289988244057
> [Add] login functionality with Email OT

- src/components/DashboardOrdersList/index.js
- src/components/OrderDetails/index.js
STORY: https://app.asana.com/0/1198717964402573/1203006460034838
> [Fix] driver auto assign issue

- src/components/GoogleMapsApiKeySetting/index.js
- src/index.js
STORY: https://app.asana.com/0/1198717964402573/1203296121985849
> Improvements

- src/components/EnterprisePromotionDetails/index.js
story: https://app.asana.com/0/1203068399720324/1203301857571516
demo: https://www.loom.com/share/2fd8b55814aa4aeb9db55d955098b4ad
> [Add] marketing promotion: users, filter

- src/components/Home/index.js
STORY: https://app.asana.com/0/1198717964402573/1203040207951255
> [Add] Project status

- src/components/BusinessZoneGoogleMaps/index.js
story: https://app.asana.com/0/1203068399720324/1203331637208866
demo: https://www.loom.com/share/2f24ccb110884c17943110fd4fd45d57
> [Update] disable name, type & zone when deliveryzone its shared

- src/components/ContentForm/index.js
- src/components/OrderingWebsite/index.js
- src/index.js
Story: https://app.asana.com/0/1200268243113852/1203305758289537
> [Feat]: ordering products home

- src/components/BusinessFormDetails/index.js
STORY: https://app.asana.com/0/1198717964402573/1203356725098862
> [Add] toast

- src/components/Settings/index.js
STORY: https://app.asana.com/0/inbox/1198717964396322/1203364915783384/1203376110609378
> [Update] order by rank

- src/components/OrderingWebsite/index.js
Story: https://app.asana.com/0/home/1200268243109536/1203305758289537
> Update: website-product

- src/components/ContentForm/index.js
- src/components/OrderingWebsite/index.js
Story: https://app.asana.com/0/1200268243113852/1203402810187080
> Update: ordering product

- src/components/BusinessZoneGoogleMaps/index.js
- src/components/DriverGroupDeliveryDetails/index.js
- src/components/DriverGroupDeliveryZone/index.js
- src/index.js
story: https://app.asana.com/0/1203068399720324/1202953542260946
demos: 
-  https://www.loom.com/share/008257424c88479c96aac980389d3030
- https://www.loom.com/share/03353256f75c42e988152d92d18ab65c
- https://www.loom.com/share/7237a77b188f4f5a91242c3321d89681
> Delivery zones features

- src/components/BusinessPaymethods/index.js
STORY: https://app.asana.com/0/1198717964402573/1203445998350919
> [Fix] payment sandbox issue

- src/components/CountryList/index.js
Story: https://app.asana.com/0/1200268243113852/1203454169898159
> [Update]: Country popup

- src/components/BannerDetails/index.js
STORY: https://app.asana.com/0/1198717964402573/1203458248409508
> [Add] banner delete function

- src/components/BusinessDeliveryZone/index.js
- src/components/BusinessZoneGoogleMaps/index.js
story: https://app.asana.com/0/0/1203452022329015/f
demo: https://www.loom.com/share/402f35f43b2c475db419f4da40d3f79b
> feedback fixes

- src/components/ImporterForm/index.js
Story: https://app.asana.com/0/1199511033583011/1203138605690722/f
Video: https://d.pr/v/HJ4Si2
> [FEAT] don't send empty keys

- src/components/CampaignUserList/index.js
- src/index.js
Story: https://app.asana.com/0/1200268243113852/1203508979612607
> [Update]: campaign on Marketing

- src/components/BusinessEta/index.js
- src/components/OrdersManage/index.js
- src/index.js
STORY: https://app.asana.com/0/1198717964402573/1202956174747201
> [Add] ETA's functionality

- src/components/BannerDetails/index.js
STORY: https://app.asana.com/0/1198717964402573/1203512546616188
> [Fix] position issue

- src/components/BusinessProductsListing/index.js
STORY: https://app.asana.com/0/1198717964402573/1203534073612228
> [Fix] subcategory issue

- src/components/BusinessAdd/index.js
- src/components/ProductStep/index.js
- src/index.js
- src/utils/index.js
Story: https://app.asana.com/0/1200268243113852/1203473061868366
> [Add]: store network

- src/components/ProductStep/index.js
Story: https://app.asana.com/0/home/1200268243109536/1203473061868366
> [Update]: ordering network

- src/components/ProductStep/index.js
Story: https://app.asana.com/0/1200268243113852/1203557719626222
> [Fix]: ordering network

- src/components/BusinessAdd/index.js
Story: https://app.asana.com/0/home/1200268243109536/1203569555078633
> [Add]: preselect city when creating new business

- src/components/DriverGroupDeliveryZone/index.js
Story: https://app.asana.com/0/1200268243113852/1203422541705554
> [update]: feedback

- src/components/BannerDetails/index.js
- src/components/BannerImageLink/index.js
- src/index.js
STORY: https://app.asana.com/0/1198717964402573/1203569562715315
> [Add] Page banner link

- src/components/UsersList/index.js
STORY: https://app.asana.com/0/1198717964402573/1203580203471887
> [Update] endpoint for business owner

- src/components/SelectPOS/index.js
- src/components/UploadMenu/index.js
- src/index.js
Story: https://app.asana.com/0/1200268243113852/1203517226859796
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1203650773072557
> [Feat]: ordering network 2

- src/components/DashboardBusinessList/index.js
- src/components/ProductStep/index.js
Story: https://app.asana.com/0/1200268243113852/1203622245623294
> [Update]: ordering network feedback

- src/components/SelectPOS/index.js
- src/components/UploadMenu/index.js
Story: https://app.asana.com/0/inbox/1200268243109536/1203657271175056/1203656452282349
> [Update]: endpoint

- src/components/SelectPOS/index.js
- src/components/UploadMenu/index.js
Story: https://app.asana.com/0/1200268243113852/1203658063963165
> [Update]: store network

- src/components/OrderingWebsite/index.js
Story: https://app.asana.com/0/1200268243113852/1203476743671995
> [Update]: ordering website

- src/components/BusinessDeliveryZoneShare/index.js
STORY: https://app.asana.com/0/1198717964402573/1203750856417297
> [Fix] delivery zone share issue

- src/components/DriversGroupDetails/index.js
Story: https://app.asana.com/0/1200268243113852/1203775763592032
> [Update]: create driver group

- src/components/ProductExtras/index.js
Story: https://app.asana.com/0/1200268243113852/1203823346677184
> [Update]: externalId for production option, suboption

- src/components/ReviewProductList/index.js
- src/index.js
Story: https://app.asana.com/0/1200268243113852/1203713044564841
> [Update]: Feedback part2

- src/components/OrdersManage/index.js
STORY: https://app.asana.com/0/1198717964402573/1203838848751201
> [Add] group order id column

- src/components/DriversList/index.js
- src/components/OrderNotification/index.js
- src/components/OrdersManage/index.js
Story: https://app.asana.com/0/0/1203929780498624/f
> [FEAT] socket improvements

- src/components/PointsWalletBusinessList/index.js
- src/components/RewardsPrograms/index.js
Story: https://app.asana.com/0/1200268243113852/1203920759623349
> [Update]: wallet settings

- src/components/OrdersManage/index.js
- src/contexts/WebsocketContext/socket.js
Story: https://app.asana.com/0/0/1203920669249760/f
Video: https://d.pr/v/ueFJww
> [FEAT] improve order socket

- src/components/BusinessAdd/index.js
Story: https://app.asana.com/0/1200268243113852/1203932166157191
> [Bug]: crash dashboard

- src/components/DashboardBusinessList/index.js
Story: https://app.asana.com/0/1200268243113852/1203895463599420
> [Update]: feedback part3

- src/components/LoginForm/index.js
Story: https://app.asana.com/0/1200268243113852/1203888189112220
> [Update]: feedback part1

- src/components/BusinessProductsListing/index.js
- src/components/BusinessReviews/index.js
- src/components/CampaignDetail/index.js
- src/components/DriversCompanyDetails/index.js
- src/components/DriversGroupDetails/index.js
- src/components/EnterprisePromotionDetails/index.js
- src/components/ProductReviews/index.js
- src/components/RecoveryActionDetail/index.js
- src/components/UserReviewDetails/index.js
STORY: https://app.asana.com/0/1198717964402573/1203717602528748
> [Update] Slider link

- src/components/UsersExportCSV/index.js
STORY: https://app.asana.com/0/1198717964402573/1203937890178708
> [Update] CSV export API

- src/components/DashboardOrdersList/index.js
- src/components/OrdersManage/index.js
story: https://app.asana.com/0/1199511033583011/1203895122272547/f
> [Fix] filter not working with country_code & city_id

- src/components/BannerDetails/index.js
- src/components/BannerImageDetails/index.js
STORY: https://app.asana.com/0/1198717964402573/1203939728081129
> [Update] Banner item add

- src/components/DashboardBusinessList/index.js
Story: https://app.asana.com/0/1200268243113852/1203976857717714
> [Update]: empty business

- src/components/BusinessAdd/index.js
Story: https://app.asana.com/0/1200268243113852/1203981538650353
> [Update]: timezone fix

- src/components/OccupationSelector/index.js
STORY: https://app.asana.com/0/1198717964402573/1203962405041667
> [Add] get occupations

- src/components/OrdersManage/index.js
Story: https://app.asana.com/0/1199511033583011/1203981538650500/f
Video: https://d.pr/v/q9h1Jw
> [FEAT] add room order register

- src/components/UsersList/index.js
Story: https://app.asana.com/0/1200268243113852/1203985818534434
> [Update]: filters on users and orders

- src/components/DashboardOrdersList/index.js
- src/components/OrdersFilter/index.js
- src/components/OrdersManage/index.js
Story: https://app.asana.com/0/1200268243113852/1203976998832718
> [Update]: filter by meta field

- src/components/DashboardOrdersList/index.js
- src/components/OrdersFilter/index.js
- src/components/OrdersManage/index.js
Story: https://app.asana.com/0/1200268243113852/1203976998832718
> [Update]: filter by metafield

- src/components/LanguageTransSpread/index.js
Story: https://app.asana.com/0/1200268243113852/1203986178543385
> Update: language issue

- src/components/BusinessAdd/index.js
Story: https://app.asana.com/0/1200268243113852/1203237025909906
> [Update]: improve business create process

- src/components/PointsWalletBusinessList/index.js
STORY: https://app.asana.com/0/1198717964402573/1204097525219510
> [Fix] token issue

- src/components/InvoiceBusinessManager/index.js
Story: https://app.asana.com/0/1200268243113852/1204057402289424
> [Update]: invoice business manager

- src/components/ProductExtraOptionDetails/index.js
Story: https://app.asana.com/0/home/1200268243109536/1204080321263252
> [Update]: product suboption preselect

- src/components/BusinessAdd/index.js
- src/components/BusinessFormDetails/index.js
STORY: https://app.asana.com/0/1198717964402573/1203952056046245
> [Update] force update the time zone api key

- src/components/DashboardOrdersList/index.js
STORY: https://app.asana.com/0/1198717964402573/1204119396827433
> [Fix] wrong orders in user details

- src/components/UserFormDetails/index.js
STORY: https://app.asana.com/0/1198717964402573/1204135916793376
> [Update] driver add as driver manager level

- src/components/BusinessDetails/index.js
story: https://app.asana.com/0/1199511033583011/1203958790153727/f
> [Feat] add spoonity apki key from stores

- src/components/BusinessAdd/index.js
story: https://app.asana.com/0/1204253144878136/1204256005754633/f
> [Fix] dashboard crash in add store

- src/components/OrderingWebsite/index.js
Story: https://app.asana.com/0/1200268243113852/1204217969736444
> [Bug]: advanced personality

- src/components/CheckoutFieldsSetting/index.js
Story: https://app.asana.com/0/1200268243113852/1204284126712270
> [Update]: show zipcode

- src/components/OrdersManage/index.js
STORY: https://app.asana.com/0/1198717964402573/1204273350738629
> [Fix] order count issue in customer profile orders

- src/components/InvoiceBusinessManager/index.js
- src/components/InvoiceDriverManager/index.js
STORY: https://app.asana.com/0/1198717964402573/1204297408879021
> [Fix] invoice for custom payment

- src/components/EnterprisePromotionDetails/index.js
STORY: https://app.asana.com/0/1198717964402573/1204271637215179
> [Fix] crash error when creating a promotion

- src/components/Messages/index.js
STORY: https://app.asana.com/0/1198717964402573/1204330702966195
> [Fix] Delivery assignment process issue

- src/components/DashboardOrdersList/index.js
- src/components/OrdersFilter/index.js
- src/components/OrdersManage/index.js
Story: https://app.asana.com/0/1200268243113852/1204335314394305
> [Update]: orders list

- src/components/ProductStep/index.js
Story: https://app.asana.com/0/inbox/1200268243109536/1204262571562442/1204262640820177
> [Update]: improve API endpoint

- src/contexts/UtilsContext/index.js
Story: https://app.asana.com/0/1200268243113852/1204381898355230
> [Bug]: distance on logistics

- src/components/BusinessDetails/index.js
- src/components/BusinessProductsListing/index.js
- src/components/CustomDomain/index.js
- src/components/OrderingWebsite/index.js
- src/index.js
Story: https://app.asana.com/0/1200268243113852/1203356559599158
> [Feat]: custom domain

- src/components/BusinessQRCodeOptions/index.js
- src/index.js
Story: https://app.asana.com/0/1200268243113852/1202437258226249
> [Feat]: QR code

- src/components/OrderDetails/index.js
STORY: https://app.asana.com/0/1198717964402573/1203695898591548
> [Add] order refund function

- src/components/AnalyticsBusinessFilter/index.js
Story: https://app.asana.com/0/1200268243113852/1204498357936088
> [Update]: city filter on business filter

- src/components/DashboardOrdersList/index.js
Story: https://app.asana.com/0/1200268243113852/1204519068768873
> [Update]: external id on orderlist

- src/components/BusinessZoneGoogleMaps/index.js
Story: https://app.asana.com/0/1200268243113852/1204470481276285
> [Bug]: allow decimal on delivery zone

- src/components/DeliveryzoneList/index.js
STORY: https://app.asana.com/0/1198717964402573/1204484511123666
> [Update] condition to get the delivery zones

- src/components/AnalyticsBusinessFilter/index.js
Story: https://app.asana.com/0/1200268243113852/1204498357936088
> [Update]: country filter on business filter

- src/components/DashboardOrdersList/index.js
- src/components/OrdersManage/index.js
Story: https://app.asana.com/0/1200268243113852/1204517801947191
> [Update]: search by driver name

- src/components/UploadAudio/index.js
- src/index.js
Story: https://app.asana.com/0/1200268243113852/1204526767405345
> [Feat]: custom sounds

- src/components/DriversGroupOrders/index.js
STORY: https://app.asana.com/0/1198717964402573/1203715148670414
> [Update] drivers group orders for new group

- src/components/DeliveryzoneList/index.js
STORY: https://app.asana.com/0/1198717964402573/1204540804054111
> [Fix] Promotion delivery zones

- src/components/OrdersManage/index.js
Story: https://app.asana.com/0/1200268243113852/1204335275236352
> [Update]: show driver group id

- src/components/DriversList/index.js
story: https://app.asana.com/0/0/1203344796632293/f
> [Feat] select companys from order details

- src/components/UsersList/index.js
Story: https://app.asana.com/0/1200268243113852/1204572644341365
> [Update]: customer filter

- src/components/DriversCompanyDetails/index.js
STORY: https://app.asana.com/0/1198717964402573/1203715204860609
> [Fix] undefined driver id

- src/components/OrderingWebsite/index.js
STORY: https://app.asana.com/0/1198717964402573/1203518580475813
> [Add] methods to get the businesses and franchises

- src/components/BusinessDeviceDetail/index.js
Story: https://app.asana.com/0/1200268243113852/1204582714534493
> [Update]: kiosk and pos management

- src/components/SelectPOS/index.js
- src/components/UploadMenu/index.js
Story: https://app.asana.com/0/1200268243113852/1204526223001675
> [Update]: add customer email

- src/components/SingleRecoveryNotification/index.js
STORY: https://app.asana.com/0/1198717964402573/1204621970220665
> [Add] change function

- src/contexts/UtilsContext/index.js
Story: https://app.asana.com/0/inbox/1200268243109536/1204664744190277/1204668688454238
> [Update]: fix language key

- src/components/BusinessAnalytics/index.js
Story: https://app.asana.com/0/1200268243113852/1204674087133639
> [Update]: business analytics feedback

- src/components/DriverGroupSetting/index.js
STORY: https://app.asana.com/0/1198717964402573/1204648949956689
> [Update] remove third party driver groups

- src/components/DriversGroupDetails/index.js
STORY: https://app.asana.com/0/1198717964402573/1204714279516327
> [Fix] add new driver group for advanced logistics

- src/components/DriverGroupSetting/index.js
STORY: https://app.asana.com/0/1198717964402573/1204728062832325
> [Update] drivers group setting

- src/components/UsersList/index.js
Story: https://app.asana.com/0/1200268243113852/1204736337069569
> [Update]: timezone

- src/components/CheckoutFieldsSetting/index.js
story: https://app.asana.com/0/1199511033583011/1204566686293757/f
> [Feat] birthdate field

- src/components/BannerDetails/index.js
- src/components/BannerImageDetails/index.js
STORY: https://app.asana.com/0/1198717964402573/1204592094895327
> [Update] banner functionality for business page

- src/components/DriversGroupDetails/index.js
STORY: https://app.asana.com/0/1198717964402573/1204771543799118
> [Add] type change function

- src/components/OrdersManage/index.js
Story: https://app.asana.com/0/1199511033583011/1204797282657296/f
> [FEAT] fix-sla-filter-order-numbers

- src/components/ProductExtraOptionDetails/index.js
- src/components/ProductExtraOptions/index.js
- src/components/ProductExtras/index.js
STORY: https://app.asana.com/0/1198717964402573/1204785506263527
> [Update] Product options

- src/components/PaymentOptionWallet/index.js
STORY: https://app.asana.com/0/1198717964402573/1204818674537746
> [Fix] wallet for customer

- src/components/ProductDetatils/index.js
- src/components/ProductExtraOptionDetails/index.js
- src/components/ProductExtraOptions/index.js
- src/components/ProductExtras/index.js
Story: https://app.asana.com/0/1200268243113852/1201126801942443
> [Update]: duplicate

- src/components/UserDetails/index.js
- src/components/UsersList/index.js
STORY: https://app.asana.com/0/1199511033583011/1204855749066381/f
> [Add] external id props

- src/components/Messages/index.js
STORY: https://app.asana.com/0/1198717964402573/1204760869658078
> Improvements for Refund Wallet

- src/constants/code-numbers.js
Story: https://app.asana.com/0/1200268243113852/1204876106954129
> [Update]: fix country code

- src/components/BusinessProductsListing/index.js
STORY: https://app.asana.com/0/1198717964402573/1204834683157319
> [Fix] business products pagination issue

- src/components/CustomOrderDetails/index.js
STORY: https://app.asana.com/0/1198717964402573/1204877440615150
> [Update] custom order details

- src/components/Messages/index.js
- src/components/UsersList/index.js
STORY: https://app.asana.com/0/1198717964402573/1204920277269419
> Fix important

- src/components/DriversList/index.js
STORY: https://app.asana.com/0/1198717964402573/1204925909633027
> [Fix] driver selector issue

- src/components/OrdersFilter/index.js
STORY: https://app.asana.com/0/1198717964402573/1204925909633074/f
> [Fix] Filter by date

- src/components/GuestCheckoutFieldsSetting/index.js
- src/index.js
Story: https://app.asana.com/0/1200268243113852/1204729057866263
> [Feat]: guest checkout field setting

- src/components/DriversList/index.js
Story: https://app.asana.com/0/1199511033583011/1204928098441341/f
> [FEAT] change

- src/components/DriversGroupDetails/index.js
Story: https://app.asana.com/0/1199511033583011/1204929069048555/f
> [FEAT] add default values

- src/components/DashboardOrdersList/index.js
- src/components/OrdersFilter/index.js
- src/components/OrdersManage/index.js
Story: https://app.asana.com/0/1200268243113852/1204920209988056
> [Update]: improvement

- src/components/DriversList/index.js
STORY: https://app.asana.com/0/1198717964402573/1204920970860609
> [Update] drivers list for socket event when driver enabled change

- src/components/Checkout/index.js
- src/components/CustomOrderDetails/index.js
Story: https://app.asana.com/0/inbox/1200268243109536/1204937705699251/1204938760663895
> [Update]: order by totoal

- src/components/DashboardOrdersList/index.js
- src/components/OrdersFilter/index.js
- src/components/OrdersManage/index.js
Story: https://app.asana.com/0/1200268243113852/1204974530333939
> [Update]: assigned values

- src/components/OrdersManage/index.js
STORY: https://app.asana.com/0/1198717964402573/1204958964611400
> [Update] driver update and driver tracking

- src/components/DashboardOrdersList/index.js
story: https://app.asana.com/0/1199511033583011/1204988784998466/f
> [Feat] filter custom orders by name, cellphone and external_id

- src/components/CustomOrderDetails/index.js
Story: https://app.asana.com/0/1200268243113852/1204996902568807
> [Update]: custom order feedback

- src/components/BusinessDeviceDetail/index.js
Story: https://app.asana.com/0/1200268243113852/1204971849289751
> [Update]: business device detail

- src/components/DashboardOrdersList/index.js
STORY: https://app.asana.com/0/1198717964402573/1205001395455903
> [Update] socket handle functions with filter options

- src/components/BusinessAnalytics/index.js
Story: https://app.asana.com/0/1200268243113852/1205055444473771
> [Update]: report issue

- src/components/DriversGroupDetails/index.js
STORY: https://app.asana.com/0/1198717964402573/1205044172415332
> [Fix] reload issue

- src/components/ProductIngredient/index.js
Story: https://app.asana.com/0/1200268243113852/1205059901157136
> [Update]: fix product ingredient

- src/components/CustomOrderDetails/index.js
Story: https://app.asana.com/0/1200268243113852/1205065508355744
> [Update]: custom order update

- src/components/DriversList/index.js
- src/components/OrderDetails/index.js
Story: https://app.asana.com/0/1200268243113852/1204981637490249
> Update: add assigment comment

- src/components/OrderDetails/index.js
Story: https://app.asana.com/0/1200268243113852/1205075744073657
> [Update]: edit order

- src/components/DriversList/index.js
- src/components/OrderDetails/index.js
Story: https://app.asana.com/0/1200268243113852/1205102353355328
> [Update]: assignment comment

- src/components/OrderDetails/index.js
Story: https://app.asana.com/0/1200268243113852/1205114451152564
> [Update]: edit order feedback

- src/components/UsersList/index.js
Story: https://app.asana.com/0/1200268243113852/1205055751054852
> [add] websocket in drivers list

- src/components/DriversList/index.js
- src/components/OrderDetails/index.js
Story: https://app.asana.com/0/1200268243113852/1205136267665529
> [Update]: driver assignment comment feedback

- src/components/OpenCartListing/index.js
- src/components/OpenCartsDetail/index.js
STORY: https://app.asana.com/0/1198717964402573/1204891491157580
> [Add] delete cart functionality

- src/components/UserDetails/index.js
- src/components/UsersList/index.js
story: https://app.asana.com/0/1199511033583011/1204945440937701/f
> [Fix] mono_session fetch parameter were missing

- src/components/BusinessProductCreator/index.js
Story: https://app.asana.com/0/1200268243113852/1205119812330113
> [Update]: product feedback

- src/components/ExportCSV/index.js
Story: https://app.asana.com/0/1200268243113852/1205138816950513
> [Update]: export csv feedback

- src/components/DriversList/index.js
- src/components/OrderDetails/index.js
Story: https://app.asana.com/0/1200268243113852/1205184392442258
> [Update]: manual assignment feedback

- src/components/CheckoutFieldsSetting/index.js
Story: https://app.asana.com/0/1199511033583011/1205014301642309
> [Update]: checkout fields by site

- src/components/AddressFieldsSetting/index.js
- src/components/CheckoutFieldsSetting/index.js
Story: https://app.asana.com/0/1200268243113852/1205014301642309
> [Update]: validation fields by site

- src/components/CampaignDetail/index.js
Story: https://app.asana.com/0/1200268243113852/1203652198072550
> [Update]: marketing feedback

- src/components/EnterprisePromotionDetails/index.js
STORY: https://app.asana.com/0/1198717964402573/1205283972442331
> [Fix] new promotion bug

- src/components/OrdersManage/index.js
- src/components/OrdersOverview/index.js
Story: https://app.asana.com/0/1200268243113852/1204845863728472
> [Update]: sentry feedback

- src/components/OrdersManage/index.js
story: https://app.asana.com/0/1201894042190305/1205181779074820/f
> [Fix] fetch status 24 and 25

- src/components/OrdersManage/index.js
Story: https://app.asana.com/0/1199511033583011/1205418496221964/f
Video: https://d.pr/v/yLVGVH
> [FEAT] disable-socket-room-driver

- src/components/DashboardOrdersList/index.js
Story: https://app.asana.com/0/0/1205420236385126/f
> [FEAT] optimize_order_data

- src/components/CountryList/index.js
story: https://app.asana.com/0/1199511033583011/1205425676859119/f
> [Fix] timeout fetch fixed sending params in order to filter info

- src/components/MetaFields/index.js
Story: https://app.asana.com/0/1198717964402573/1205366264002350/f
> [FIX] Load MetaFields immediately

- src/components/ExportCSV/index.js
Story: https://app.asana.com/0/1199511033583011/1205511820604526/f
> [CHORE] Remove verbose logging

- src/components/DashboardOrdersList/index.js
Story: https://app.asana.com/0/1199511033583011/1205539662126712/f
> [FEAT] delivery dashboard improvements

- src/contexts/OrderingContext/index.js
- src/index.js
Story: https://app.asana.com/0/1203637309747495/1205380260085848/f
> Optimization load

- src/contexts/OrderingContext/index.js
- src/index.js
This reverts commit 0697afceb33fe5c7e359e6d497b39c92c02d4557.
> Revert "Optimization load"

- src/components/DashboardOrdersList/index.js
- src/components/OrdersFilter/index.js
story: https://app.asana.com/0/0/1205531806034306/f
> [Feat] driver group general filter

- src/components/OrdersFilter/index.js
story: https://app.asana.com/0/0/1205531806034306/f
> [Fix] page goes to white screen

- src/components/OrderDetails/index.js
story: https://app.asana.com/0/0/1205570586645216/f
> [Update] update order detail without socket

- src/components/DriversList/index.js
- src/components/OrderDetails/index.js
story: https://app.asana.com/0/0/1205570586645200/f
> [Fix] abort fetch when change order detail

- src/components/DriversList/index.js
- src/components/OrdersManage/index.js
- src/contexts/OrderContext/index.js
Story: https://app.asana.com/0/1199511033583011/1204408673936303/f
> [FEAT] improvement-use-batch-sockets

- src/components/OrdersManage/index.js
Story: https://app.asana.com/0/1205563083891731/1205578267897104/f
> [FEAT] fix-socket-issues-order-details

- src/components/DriversList/index.js
Story : https://app.asana.com/0/1205563083891731/1205578267897104/f
> [FEAT] fix-socket-issues-orders

- src/components/OrdersManage/index.js
Story: https://app.asana.com/0/1205563083891731/1205539662126828/f
> [FEAT] improvement-use-franchise-images

- src/components/SettingsLogs/index.js
- src/index.js
story: https://app.asana.com/0/0/1205712930874581/f
> [Feat] settings logs page

- src/components/SettingsLogs/index.js
story: https://app.asana.com/0/0/1205712930874581/f
> [Fix] import fix

- src/components/InvoiceDriverManager/index.js
story: https://app.asana.com/0/1199511033583011/1205723866912033/f
> [Fix] add orders paid with wallets in driver invoices

- src/components/OrdersManage/index.js
Story: https://app.asana.com/0/0/1205806633088965/f
> [FEAT] add agent column

- src/components/BusinessDeliveryDetails/index.js
- src/components/BusinessDetails/index.js
- src/components/BusinessMenu/index.js
- src/components/BusinessProductsListing/index.js
- src/components/ProductDetatils/index.js
- src/components/ProductExtraOptions/index.js
- src/components/ProductExtras/index.js
Story: https://app.asana.com/0/1205433118337635/1205865654498023/f
> [FEAT] improvement-business-&-product-loads

- src/components/UsersList/index.js
story: https://app.asana.com/0/1199511033583011/1205713640269473/f
> [Feat] able to mark as not busy

- src/components/OrdersManage/index.js
> Channel addition

- src/components/UsersExportCSV/index.js
Added user csv filter condition
> Added user csv filter condition

- src/components/OrdersManage/index.js
> channel issue fixation

- src/components/CustomOrderDetails/index.js
Story: https://app.asana.com/0/1199511033583011/1206073147860570/f
> [FEAT] search product by filter

- src/components/DashboardOrdersList/index.js
- src/components/ExportCSV/index.js
Story: https://app.asana.com/0/1199511033583011/1206155034056598/f
> [FEAT] add-filter-by-franchise

- src/components/OrdersFilter/index.js
> [FEAT] filter-value-context

- src/components/GoogleAutocompleteInput/index.js
> [FEAT] improve zipcode info

- src/components/BusinessFormDetails/index.js
Story: https://app.asana.com/0/0/1206315028118838/f
Video: https://d.pr/v/LmBK9l
> [FEAT] add-option-selector-disable-reason

- src/components/DashboardOrdersList/index.js
Story: https://app.asana.com/0/0/1206352966813541/f
> [FEAT] fix-filters-bug

- src/components/UsersFilter/index.js
- src/components/UsersList/index.js
Story: https://app.asana.com/0/1199511033583011/1206351585168322/f
> [FEAT] improve-loading-filter-customers

- src/components/UsersFilter/index.js
- src/components/UsersList/index.js
Story: https://app.asana.com/0/1199511033583011/1206351585168322/f
> Add-external-user-id-filter

- src/components/DashboardOrdersList/index.js
Story: https://app.asana.com/0/1199511033583011/1206393051997698/f
> [FEAT] fix-filters-updates

- src/components/DashboardOrdersList/index.js
Story: https://app.asana.com/0/0/1206401433217770/f
> [FEAT] driver group filter functionality

- src/components/DriversList/index.js
Story: https://app.asana.com/0/0/1206386116597453/f
> driver-filter-all-in-one

- src/components/DriversGroupDetails/index.js
Story: https://app.asana.com/0/1206487310134639/1206038699169905/f
> [FEAT] add-temporary-drivers

- src/components/DriversGroupDetails/index.js
Story: https://app.asana.com/0/0/1206545648329909/f
> [FEAT] feedback-temorary-driver

- src/components/DriversGroupDetails/index.js
Story: https://app.asana.com/0/0/1206582124401852/f
> [FEAT] feedback-temporary-drivers

- src/components/BusinessLogs/index.js
- src/index.js
Story: https://app.asana.com/0/1206487310134639/1206430623900544/f
> [FEAT] add business logs

- src/components/OrdersFilter/index.js
Story: https://app.asana.com/0/0/1206586054216160/f
> [FEAT] fix-user-timezone-order-filter-today-yesterday

- src/components/DriversList/index.js
Story: https://app.asana.com/0/1199511033583011/1206673916412406/f
> [FEAT] fix crash

- src/components/DriversGroupsList/index.js
Story: https://app.asana.com/0/1199511033583011/1206705019735370/f
> [FEAT] fix-crash-delivery business groups

- src/components/BusinessDeliveryZone/index.js
Story: https://app.asana.com/0/1199511033583011/1206582161459432/f
> [FEAT] add simplifyPolygon

- src/components/DashboardOrdersList/index.js
Story: https://app.asana.com/0/0/1207038343797960/f
> [FEAT] fix filter cellphone

- package.json
- yarn.lock
Story: https://app.asana.com/0/0/1207592433611703/f
> [FEAT] remove sentry

- src/components/ProductDetatils/index.js
- src/components/ProductExtras/index.js
Story: https://app.asana.com/0/1164464536714178/1207727425135135/f
> [FEAT] fix-product-extra-state

- src/components/ProductExtraOptionDetails/index.js
Story: https://app.asana.com/0/1164464536714178/1207126872846735/f
> [FEAT] handle-change-settings-state

- src/components/BusinessProductsCategoyDetails/index.js
Story: https://app.asana.com/0/1164464536714178/1207649943125832/f
> chore: Remove 'rank' key from changes in BusinessProductsCategoyDetails

- src/components/BusinessMenuOptions/index.js
Story: https://app.asana.com/0/1164464536714178/1207126872846736/f
> [FEAT] shared menu

- src/components/ProductDetatils/index.js
Story: https://app.asana.com/0/1164464536714178/1207781355826077/f
> [FEAT] add-version-2-product

- src/components/BusinessProductsCategoyDetails/index.js
Story: https://app.asana.com/0/1164464536714178/1208091184837989/f
> chore: Add 'snooze_until' key to categoryKeyOptions in BusinessProductsCategoyDetails

- src/components/BusinessProductsCategoyDetails/index.js
Story: https://app.asana.com/0/1199567559269427/1208091184837989/f
> chore: Refactor BusinessProductsCategoyDetails add missed change for keys

- src/components/BusinessMenu/index.js
Story: https://app.asana.com/0/1164464536714178/1208468048115182/f
> Refactor: Improve loading state handling in BusinessMenu component

- src/components/BusinessWalletsList/index.js
- src/components/PaymentOptionStripeLink/index.js
- src/index.js
Story: https://app.asana.com/0/1164464536714178/1208602367363143/f
> Refactor BusinessWalletsList and PaymentOptionStripeLink components

- src/components/BusinessMenu/index.js
Story: https://app.asana.com/0/1164464536714178/1208710857605764/f
> Refactor: Update fetch parameters in BusinessMenu to include propsToFetchMenuChannel

- src/components/BusinessMenuOptions/index.js
Story: https://app.asana.com/0/1164464536714178/1208629113904671/f
> Refactor: Update setCurrentMenu to handle loading state and restructure menu object

- src/components/GoogleAutocompleteInput/index.js
- src/components/GoogleMaps/index.js
- src/components/GpsButton/index.js
Story: https://app.asana.com/0/1164464536714178/1209126625571252/f
> feat: Enhance address handling in Google Autocomplete and Maps components to include additional address components

- src/components/DashboardOrdersList/index.js
- src/components/OrdersFilter/index.js
Story: https://app.asana.com/0/1164464536714178/1209127099331032/f
> refactor: Remove direct timeStatus handling and update filterValues initialization in DashboardOrdersList and OrdersFilter components

- src/components/DashboardOrdersList/index.js
Story: https://app.asana.com/0/1164464536714178/1209174571156174/f
> refactor: Simplify column visibility update logic in DashboardOrdersList component

- src/components/OrdersManage/index.js
Story: https://app.asana.com/0/1164464536714178/1209230098814226
> refactor: Optimize orderColumns configuration with base column settings in OrdersManage

- src/components/BusinessMenuShare/index.js
Story: https://app.asana.com/0/1164464536714178/1209353762113512
> feat: Add setCurrentMenu support in BusinessMenuShare component

- src/components/DriverGroupSetting/index.js
Story: https://app.asana.com/0/1164464536714178/1209353762113520
> feat: Enhance DriverGroupSetting to support driver manager group management

- src/components/Messages/index.js
Story: https://app.asana.com/0/1164464536714178/1209353762113523
> fix: Update message author display logic with fallback translations

- src/components/GoogleMaps/index.js
- src/components/WrapperGoogleMaps/index.js
Story: https://app.asana.com/0/1164464536714178/1209333710289645
> feat: Improve Google Maps component error handling and data validation

- src/components/OrderingWebsite/index.js
Story: https://app.asana.com/1/306583973076188/project/1164464536714178/task/1209599317137467
> feat: Add default values for homepage and footer content in theme settings

- src/components/DriversGroupsList/index.js
Story: https://app.asana.com/0/1164464536714178/1209509515621448/f
> fix: Update data fetching logic in DriversGroupsList component based on search value

- src/components/DriversList/index.js
- Add support for setting order based on selected driver location
- Introduce new props: setOrderForMap and orderForMap
- Update useEffect hooks to manage driver selection and order state
> feat: Enhance DriversList component with ordering functionality

- src/components/DriverGroupSetting/index.js
Story: https://app.asana.com/1/306583973076188/project/1164464536714178/task/1210345223592400?focus=true
> feat: Add select all drivers functionality in DriverGroupSetting component
